# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "04bf2409ba3e5343348e9ad95c303300"
name = "ethelm-checkout-extension"
handle = "ethelm-checkout-extension"
application_url = "https://gossip-styles-mauritius-saturn.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "thebrandsofwatches.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://gossip-styles-mauritius-saturn.trycloudflare.com/auth/callback",
  "https://gossip-styles-mauritius-saturn.trycloudflare.com/auth/shopify/callback",
  "https://gossip-styles-mauritius-saturn.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
