# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bded50055b155209f6b5def0b7e8c6c3"
name = "Ethelm-Checkout-UI-Ext"
handle = "ethelm-checkout-ui-ext"
application_url = "https://cycle-farmers-modeling-balloon.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "extensionstesting123.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://cycle-farmers-modeling-balloon.trycloudflare.com/auth/callback",
  "https://cycle-farmers-modeling-balloon.trycloudflare.com/auth/shopify/callback",
  "https://cycle-farmers-modeling-balloon.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
